Models/Stock.cs
namespace BookShoppingCartMvcUI.Models
{
    
    public class Stock
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public int Quantity { get; set; }

        public Book? Book { get; set; }
    }
}

Controllers/StockController.cs
using BookShoppingCartMvcUI.Models.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookShoppingCartMvcUI.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class StockController : Controller
    {
        private readonly IStockRepository _stockRepo;

        public StockController(IStockRepository stockRepo)
        {
            _stockRepo = stockRepo;
        }

        public async Task<IActionResult> Index(string sTerm = "")
        {
            var stocks = await _stockRepo.GetStocks(sTerm);
            return View(stocks);
        }

        public async Task<IActionResult> ManangeStock(int bookId)
        {
            var existingStock = await _stockRepo.GetStockByBookId(bookId);
            var stock = new StockDTO
            {
                BookId = bookId,
                Quantity = existingStock != null
            ? existingStock.Quantity : 0
            };
            return View(stock);
        }

        [HttpPost]
        public async Task<IActionResult> ManangeStock(StockDTO stock)
        {
            if (!ModelState.IsValid)
                return View(stock);
            try
            {
                await _stockRepo.ManageStock(stock);
                TempData["successMessage"] = "Stock is updated successfully.";
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "Something went wrong!!";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Stock/Index.cshtml
@model IEnumerable<StockDisplayModel>
@{
    Layout = "_AdminLayout";
}
<h2>Stocks</h2>

<form asp-action="Index" method="get" class="my-2 d-flex gap-2">
    <input type="text" name="sTerm" class="form-control w-25" placeholder="Search by book" />
    <button type="submit" class="btn btn-primary">Find</button>
    <a asp-action="Index" asp-controller="Stock" class="btn btn-primary">Clear</a>
</form>

<table class="table table-bordered">
  <tr>
    <th>Book</th>
    <th>Stock</th>
    <th>Actions</th>
  </tr>
  @foreach(var item in Model)
  {
    <tr>
      <td>@item.BookName</td>
      <td>@item.Quantity</td>
      <td>
         <a asp-action="ManangeStock" asp-controller="Stock" asp-route-bookId="@item.BookId" class="btn btn-info"> Update Stock</a>
      </td>
    </tr>
  }
</table>

Views/Stock/ManangeStock.cshtml
@model StockDTO
@{
    Layout = "_AdminLayout";
}

<div style="width:50%">
    <h2> Manage Stock </h2>
    <a asp-action="Index" asp-controller="Stock" class="btn btn-primary">Back</a>
    <form asp-action="ManangeStock">
        <input type="hidden" asp-for="BookId" />

        <div class="my-2">
            <label>Quantity</label>
            <input type="number" class="form-control" asp-for="Quantity" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>

        <div class="my-2">
            <button type="submit" class="btn btn-info">Update</button>
        </div>
    </form>
</div>