Models/Genre.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace BookShoppingCartMvcUI.Models
{
    public class Genre
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(40)]
        public string GenreName { get; set; }
        public List<Book> Books { get; set; }
    }
}

Controllers/GenreController.cs
using BookShoppingCartMvcUI.Models.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookShoppingCartMvcUI.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class GenreController : Controller
    {
        private readonly IGenreRepository _genreRepo;

        public GenreController(IGenreRepository genreRepo)
        {
            _genreRepo = genreRepo;
        }

        public async Task<IActionResult> Index()
        {
            var genres = await _genreRepo.GetGenres();
            return View(genres);
        }

        public IActionResult AddGenre()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddGenre(GenreDTO genre)
        {
            if (!ModelState.IsValid)
            {
                return View(genre);
            }
            try
            {
                var genreToAdd = new Genre { GenreName = genre.GenreName, Id = genre.Id };
                await _genreRepo.AddGenre(genreToAdd);
                TempData["successMessage"] = "Genre added successfully";
                return RedirectToAction(nameof(AddGenre));
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "Genre could not added!";
                return View(genre);
            }

        }

        public async Task<IActionResult> UpdateGenre(int id)
        {
            var genre = await _genreRepo.GetGenreById(id);
            if (genre is null)
                throw new InvalidOperationException($"Genre with id: {id} does not found");
            var genreToUpdate = new GenreDTO
            {
                Id = genre.Id,
                GenreName = genre.GenreName
            };
            return View(genreToUpdate);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateGenre(GenreDTO genreToUpdate)
        {
            if (!ModelState.IsValid)
            {
                return View(genreToUpdate);
            }
            try
            {
                var genre = new Genre { GenreName = genreToUpdate.GenreName, Id = genreToUpdate.Id };
                await _genreRepo.UpdateGenre(genre);
                TempData["successMessage"] = "Genre is updated successfully";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "Genre could not updated!";
                return View(genreToUpdate);
            }

        }

        public async Task<IActionResult> DeleteGenre(int id)
        {
            var genre = await _genreRepo.GetGenreById(id);
            if (genre is null)
                throw new InvalidOperationException($"Genre with id: {id} does not found");
            await _genreRepo.DeleteGenre(genre);
            return RedirectToAction(nameof(Index));

        }

    }
}

Views/Genre/AddGenre.cshtml
@using BookShoppingCartMvcUI.Models.DTOs
@model GenreDTO
@{
    Layout = "_AdminLayout";
}
@* @Html.ValidationSummary() *@
<div style="width:50%">
    <h2> Add Genre </h2>
    <a asp-action="Index" asp-controller="Genre" class="btn btn-primary">Back</a>
    <form asp-action="AddGenre">
        @* <input type="hidden" asp-for="Id" /> *@

        <div class="my-2">
            <label>Genre</label>
            <input type="text" class="form-control" asp-for="GenreName" />
            <span asp-validation-for="GenreName" class="text-danger"></span>
        </div>

        <div class="my-2">
            <button type="submit" class="btn btn-info">Add</button>
        </div>
    </form>
</div>

Views/Genre/Index.cshtml
@model IEnumerable<Genre>
@{
    Layout = "_AdminLayout";
}

<h2>Genres</h2>

<a asp-action="AddGenre" asp-controller="Genre" class="btn btn-primary">Add More</a>

<table class="table table-striped my-2">
    <tr>
        <th>Genre</th>
        <th>Action</th>
    </tr>

    @foreach (var genre in Model)
    {
        <tr>
            <td>@genre.GenreName</td>
            <td>
                <a asp-action="UpdateGenre" asp-controller="Genre" asp-route-id="@genre.Id" class="btn btn-success">Edit</a>
                <a asp-action="DeleteGenre" asp-controller="Genre" asp-route-id="@genre.Id" class="btn btn-danger" onclick="return window.confirm('Are you sure?')">Delete</a>
            </td>
        </tr>
    }
</table>

Views/Genre/UpdateGenre.cshtml
@model GenreDTO
@{
    Layout = "_AdminLayout";
}
@* @Html.ValidationSummary() *@
<div style="width:50%">
    <h2> Update Genre </h2>
    <a asp-action="Index" asp-controller="Genre" class="btn btn-primary">Back</a>
    <form asp-action="UpdateGenre">
        <input type="hidden" asp-for="Id" />

        <div class="my-2">
            <label>Genre</label>
            <input type="text" class="form-control" asp-for="GenreName" />
            <span asp-validation-for="GenreName" class="text-danger"></span>
        </div>

        <div class="my-2">
            <button type="submit" class="btn btn-info">Update</button>
        </div>
    </form>
</div>